<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * form file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
 
 	PS::_rcf( $this->getAppBaseUrl() . '/css/form.css' );

	if ( Yii::app()->user->hasFlash( 'commentSubmitted' ) )
	{
		echo PS::tag( 'h3', array(), 'Thanks!' );
		echo '<div class="yiiForm">' . Yii::app()->user->getFlash( 'commentSubmitted' ) . '</div>';
		return;
	}

	//	Build our form options array...
	$_arFormOpts = array( 
		
		//	Form Title
		'formTitle' => 'Leave a Comment',
		'formTitleTag' => 'h3',
	
		//	Gimme jQuery UI styling
		'uiStyle' => PS::UI_JQUERY,
		
		//	Our model
		'formModel' => $comment,
		
		//	We want error summary...
		'errorSummary' => true,
		
		//	Our form fields...
		'fields' => array(
			array( PS::TEXT, 'author_name_text', array( 'size' => 60, 'maxlength' => 255 ) ),
			array( PS::TEXT, 'email_addr_text', array( 'class' => 'email', 'size' => 60, 'maxlength' => 255, 'hint' => 'Your email address will not be published.' ) ),
			array( PS::TEXT, 'url_text', array( 'class' => 'url', 'size' => 60, 'maxlength' => 255 ) ),
			array( PS::CKEDITOR, 'content_text' ),
			array( PS::CAPTCHA, 'verifyCode', array( 'condition' => '( Yii::app()->user->isGuest && extension_loaded( \'gd\' ) )' ) ),
			array( 'submit', $update ? 'Update' : 'Save', array( 'id' => 'btnSubmit', 'name' => 'submitComment', 'jqui' => true, 'icon' => 'disk' ) ),
		),
		
		//	And validate the form too
		'validate' => true, 
		
		//	Set some validation options
		'validateOptions' => array(
			'messages' => array(
				'Comment[author_name_text]' => array(
					'required' => 'Anonymous commenting is not allowed. We need your name.',
				),
				'Comment[email_addr_text]' => array(
					'required' => 'You must enter your email address',
				),
				'Comment[content_text]' => array(
					'required' => 'You must enter a comment.',
				),
			),
		), 
	);

	CPSForm::create( $_arFormOpts );	