<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * form file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
	CPSHelp::_rcf( '/css/form.css' );

	//	I don't like this, I prefer bold-faced labels
	PS::$afterRequiredLabel = null;
	
//	Uncomment for automatic tooltips
//	CPSjqToolsWrapper::create( 'tooltip', array( 'target' => '#ps-edit-form :input', 'tip' => '.ps-auto-tooltip', 'position' => 'center right', 'offset' => array( -2, 10 ), 'effect' => 'fade', 'opacity' => 0.7 ) );
?>
<div class="ps-edit-container">
	<div class="yiiForm">
<?php
		echo PS::beginForm( '', 'POST', 
			array( 
				'validate' => true, 
				'validateOptions' => array(
					'errorClass' => 'ps-validate-error',
					'ignoreTitle' => true,
// @todo Place your extra validation options here...
//					'rules' => array(
//						'model_name[column_name] => array(
//							'rule' => rule options,
//					),
//					'messages' => array(
//						'model_name[column_name] => array(
//							'rule_name' => 'message',
//						),
//					),
				), 
				'id' => 'ps-edit-form', 
				'name' => 'ps-edit-form'
			)
		);
	
			echo PS::errorSummary( $model );
			echo PS::field( PS::TEXT, $model, 'post_id' );
			echo PS::field( PS::TEXTAREA, $model, 'content_text', array( 'rows' => 6, 'cols' => 50 ) );
			echo PS::field( PS::TEXTAREA, $model, 'content_display_text', array( 'rows' => 6, 'cols' => 50 ) );
			echo PS::field( PS::TEXT, $model, 'status_nbr' );
			echo PS::field( PS::TEXT, $model, 'author_name_text', array( 'size' => 60, 'maxlength' => 255 ) );
			echo PS::field( PS::TEXT, $model, 'email_addr_text', array( 'size' => 60, 'maxlength' => 255 ) );
			echo PS::field( PS::TEXT, $model, 'url_text', array( 'size' => 60, 'maxlength' => 255 ) );

			echo $model->showDates();
		echo PS::endForm();
?>
	</div>
</div>