<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * create view file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
	echo CPSForm::formHeader( 'New Comment', 
		array( 
			'save' => array(
				'label' => 'Save',
				'url' => '_submit_',
				'icon' => 'disk',
			),
			
			'cancel' => array(
				'label' => 'Cancel',
				'url' => array( 'admin' ),
				'icon' => 'cancel',
			),
			
			'return' => array(
				'label' => 'Comment Manager',
				'url' => array( 'admin' ),
				'icon' => 'arrowreturnthick-1-w',
			),
		)
	);

echo $this->renderPartial( '_form', array(
	'model' => $model,
	'update' => false,
));