<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * update view file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
	echo CPSForm::formHeader( 'Edit Comment: ' . $model->id, 
		array( 
			'save' => array(
				'label' => 'Save',
				'url' =>  '_submit_',
				'icon' => 'disk',
			),
			
			'cancel' => array(
				'label' => 'Cancel',
				'url' => array( 'admin' ),
				'icon' => 'cancel',
			),
			
			'delete' => array(
				'label' => 'Delete',
				'url' => array( 'delete' ),
				'confirm' => 'Do you really want to delete this Comment?',
				'icon' => 'trash',
			),
		)
	);
	
	echo $this->renderPartial( '_form', array(
		'model' => $model,
		'update' => true,
	));