<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * update view file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id: update.php 367 2010-01-16 04:29:24Z jerryablan@gmail.com $
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
	PS::_rcf( Yii::app()->baseUrl . '/css/form.css' );

	//	I don't like this, I prefer bold-faced labels
	PS::$afterRequiredLabel = null;
	
	echo CPSForm::formHeaderEx( 'Edit Post #' . $model->id, array( 'menuButtons' => array( 'save', 'cancel', 'delete' ) ) );
	
	echo $this->renderPartial( '_form', array(
		'model' => $model,
		'update' => true,
	));