<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * admin view file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 *                                                                   
 */
 	
 	//	Load our grid css
 	CPSHelp::_rcf( Yii::app()->baseUrl . '/css/grid.css' );
 
 	//	Build the header
	echo CPSForm::formHeader( 'Post Manager', 
		array( 'new' => 
			array(
				'label' => 'New Post',
				'url' => array( 'create' ),
				'icon' => 'circle-plus',
			)
		)
	);

	//	Build the grid
	$_arOpts = array(
		'actions' => array( 
			CPSDataGrid::ACTION_GENERIC => array(
				'label' => 'Publish',
				'url' => array( 'publish', 'id' => '%%id%%' ),
				'confirm' => 'Publish this post?',
				'icon' => 'check',
			),
			CPSDataGrid::ACTION_EDIT => 'update',
			CPSDataGrid::ACTION_DELETE,
		),
		'sort' => $sort,
		'pages' => $pages,
		'columns' => array( 'title_text', 'statusText', 'comment_count_nbr', 'create_date' ),
		'pagerOptions' => array( 'header' => '' ),
		'dataItemName' => 'Post',
	);
	
	echo CPSDataGrid::createEx( $models, $_arOpts );