<refentry id="{@id}">
 <refnamediv>
  <refname>CPSComponent -- The base component</refname>
  <refpurpose>Extends the Yii base component object adding functionality</refpurpose>
 </refnamediv>
 <refsynopsisdiv>
  <author>
   Jerry Ablan
   <authorblurb>
    {@link mailto:yii@pogostick.com yii@pogostick.com}
   </authorblurb>
  </author>
 </refsynopsisdiv>
 <refsect1 id="{@id intro}">
  <title>Why do I need a mini-framework inside a framework?</title>
  <para>My thought was that if it could be even easier to extend Yii, more people would build extensions.</para>
 </refsect1>
  <refsect1 id="{@id references}">
  <title>References for learning how to use phpDocumentor</title>
  <para>
   <itemizedlist>
    <listitem>
	 <para>aaaf</para>
	</listitem>
   </itemizedlist>
  </para>
 </refsect1>
</refentry>

