<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * CommentController class file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
class CommentController extends CPSCRUDController
{
	//********************************************************************************
	//* Public Methods
	//********************************************************************************
	
	public function init()
	{
		//	Phone home...
		parent::init();
		
		//	Set model name...
		$this->setModelName( 'Comment' );
	}

	/**
	 * Default admin action. Change conditions for your system
	 *
	 */
	public function actionAdmin( $arExtraParams = array(), $oCriteria = null )
	{
		//	Add your own functionality...
		return parent::actionAdmin( $arExtraParams, $oCriteria );
	}

}