<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * PostController class file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
class PostController extends CPSCRUDController
{
	//********************************************************************************
	//* Public Methods
	//********************************************************************************
	
	public function init()
	{
		//	Phone home...
		parent::init();
		
		//	Set model name...
		$this->setModelName( 'Post' );
	}

	/**
	 * Default admin action. Change conditions for your system
	 *
	 */
	public function actionAdmin( $arExtraParams = array(), $oCriteria = null )
	{
		//	Add your own functionality...
		return parent::actionAdmin( $arExtraParams, $oCriteria );
	}
	
	//********************************************************************************
	//* Actions
	//********************************************************************************
	
	/**
	* Creates a post
	*/
	public function actionCreate()
	{
		$_oPost = new Post();
		
		if ( isset( $_POST, $_POST['Post'] ) )
		{
			$_oPost->attributes = $_POST['Post'];
			
			if ( isset( $_POST['previewPost'] ) )
				$_oPost->validate();
			else 
			{
				if ( isset( $_POST['submitPost'] ) && $_oPost->save() )
					$this->redirect( array( 'show', 'id' => $_oPost->id ) );
			}
		}
		
		$this->render( 'create', array( 'model' => $_oPost ) );
	}

	/**
	* Updates a post
	*/
	public function actionUpdate()
	{
		$_iId = PS::o( $_GET, 'id' );
		
		if ( null !== ( $_oPost = Post::model()->findByPk( $_iId ) ) )
		{
			if ( isset( $_POST, $_POST['Post'] ) )
			{
				$_oPost->attributes = $_POST['Post'];

				if ( isset( $_POST['previewPost'] ) )
					$_oPost->validate();
				else 
				{
					if ( isset( $_POST['submitPost'] ) && $_oPost->save() )
						$this->redirect( array( 'show', 'id' => $_oPost->id ) );
				}
			}
		}
		
		$this->render( 'update', array( 'model' => $_oPost ) );
	}

	/**
	* Check if user is logged in.
	* @returns Post
	*/
	public function loadModel()
	{
		if ( null === ( $_oModel = parent::loadModel() ) )
		{
			if ( Yii::app()->user->isGuest && $_oModel->status_nbr != Post::STATUS_PUBLISHED )
				throw new CHttpException( 404, 'The requested post does not exist.' );
		}
		
		return $_oModel;
	}

}