<?php
/*
 * This file is part of the psYiiExtensions package.
 * 
 * @copyright Copyright &copy; 2009 Pogostick, LLC
 * @link http://www.pogostick.com Pogostick, LLC.
 * @license http://www.pogostick.com/licensing
 */

/**
 * Include various options with generated code
 * 
 * @package 	psYiiExtensions.templates
 * @subpackage 	crud
 * 
 * @author 		Jerry Ablan <jablan@pogostick.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */

 //	Get the defaults from the config file...
if ( ! $_sCopyright = Yii::app()->params['@copyright'] ) $_sCopyright = 'Copyright &copy; ' . date( 'Y' ) . ' You!';
if ( ! $_sAuthor = Yii::app()->params['@author'] ) $_sAuthor = 'Your Name <your@email.com>';
if ( ! $_sLink = Yii::app()->params['@link'] ) $_sLink = 'http://wwww.you.com';
if ( ! $_sPackage = Yii::app()->params['@package'] ) $_sPackage = Yii::app()->id;
if ( ! isset( $baseClass ) ) $baseClass = 'CPSModel';
if ( ! isset( $dbToUse ) ) $dbToUse = 'db';

//	Output the header...
echo <<<HTML
<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright {$_sCopyright}
 * @link {$_sLink}
 */

/**
 * {$className} file
 * 
 * @package 	{$_sPackage}
 * @subpackage 	
 * 
 * @author 		{$_sAuthor}
 * @version 	SVN: \$Id\$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
HTML;
