<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * Comment file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
class Comment extends BaseModel
{
	//********************************************************************************
	//* Code Information
	//********************************************************************************
	
	/**
	* This model was generated from database component 'db'
	*
	* The followings are the available columns in table 'comment_t':
	*
	* @var integer $id
	* @var integer $post_id
	* @var string $content_text
	* @var string $content_display_text
	* @var integer $status_nbr
	* @var string $author_name_text
	* @var string $email_addr_text
	* @var string $url_text
	* @var string $create_date
	* @var string $lmod_date
	*/
	 
	//********************************************************************************
	//* Public Methods
	//********************************************************************************
	
	/**
	* Returns the static model of the specified AR class.
	* @return CActiveRecord the static model class
	*/
	public static function model( $sClassName = __CLASS__ )
	{
		return parent::model( $sClassName );
	}
	
	/**
	* @return string the associated database table name
	*/
	public function tableName()
	{
		return self::getTablePrefix() . 'comment_t';
	}

	/**
	* @return array validation rules for model attributes.
	*/
	public function rules()
	{
		return array(
			array( 'author_name_text', 'length', 'max' => 255 ),
			array( 'email_addr_text', 'length', 'max' => 255 ),
			array( 'url_text', 'length', 'max' => 255 ),
			array( 'content_text, status_nbr, author_name_text, email_addr_text', 'required' ),
			array( 'status_nbr', 'numerical', 'integerOnly' => true ),
		);
	}

	/**
	* @return array relational rules.
	*/
	public function relations()
	{
		return array(
			'post' => array( self::BELONGS_TO, 'Post', 'post_id' ),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'post_id' => 'Post',
			'content_text' => 'Content Text',
			'content_display_text' => 'Content Display Text',
			'status_nbr' => 'Status Nbr',
			'author_name_text' => 'Author Name Text',
			'email_addr_text' => 'Email Addr Text',
			'url_text' => 'Url Text',
			'create_date' => 'Create Date',
			'lmod_date' => 'Lmod Date',
		);
	}

	/**
	 * @return array customized tooltips (attribute=>tip)
	 */
	public function attributeTooltips()
	{
		return array(
			'id' => 'Id',
			'post_id' => 'Post',
			'content_text' => 'Content Text',
			'content_display_text' => 'Content Display Text',
			'status_nbr' => 'Status Nbr',
			'author_name_text' => 'Author Name Text',
			'email_addr_text' => 'Email Addr Text',
			'url_text' => 'Url Text',
			'create_date' => 'Create Date',
			'lmod_date' => 'Lmod Date',
		);
	}
}
